"""empty message

Revision ID: 39758f2ff183
Revises: 767157cddd73
Create Date: 2024-01-04 03:43:44.477028

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39758f2ff183'
down_revision: Union[str, None] = '767157cddd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column(
        'parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('location_parent_id_fkey',
                          'location', 'location', ['parent_id'], ['id'])
    op.alter_column('proxy', 'server',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
    conn = op.get_bind()
    conn.execute(
        sa.text("INSERT INTO location(name, parent_id) Values('Moscow', 1)"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxy', 'server',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_constraint('location_parent_id_fkey',
                       'location', type_='foreignkey')

    conn = op.get_bind()
    conn.execute(sa.text("TRUNCATE TABLE location CASCADE;"))
    op.drop_column('location', 'parent_id')

    # ### end Alembic commands ###
