"""empty message

Revision ID: 3e5915bab354
Revises: e115b8fdcf7e
Create Date: 2023-12-25 09:09:22.802014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5915bab354'
down_revision: Union[str, None] = 'e115b8fdcf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('reason', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'reason')
    # ### end Alembic commands ###
