"""empty message

Revision ID: 7288258e2971
Revises: 3e5915bab354
Create Date: 2023-12-25 19:18:10.749014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7288258e2971'
down_revision: Union[str, None] = '3e5915bab354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_service',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.add_column('error', sa.Column(
        'parsed_service_id', sa.Integer(), nullable=False))
    op.create_foreign_key('error_parsed_service_id_fkey', 'error', 'parsed_service', [
                          'parsed_service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM parsed_service"))
    op.drop_constraint('error_parsed_service_id_fkey',
                       'error', type_='foreignkey')
    op.drop_column('error', 'parsed_service_id')
    op.drop_table('parsed_service')
    # ### end Alembic commands ###
