"""empty message

Revision ID: e115b8fdcf7e
Revises: f4032ede803d
Create Date: 2023-12-25 08:54:36.306581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e115b8fdcf7e'
down_revision: Union[str, None] = 'f4032ede803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'created_at')
    # ### end Alembic commands ###
