version: "3.8"

services:
  app:
    build: ./app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - 8004:8000
    env_file:
      - .env
    depends_on:
      - db_postgres
      - db_redis
    networks:
      - proxy-network

  db_postgres:
    build:
      context: ./db_postgres
      dockerfile: Dockerfile
    volumes:
      - ./db_postgres/data:/var/lib/postgresql/data
    env_file:
      - .db.env
    expose:
      - 5432
    networks:
      - proxy-network
    ports:
      - "5432:5432"

  db_redis:
    build:
      context: ./db_redis
      dockerfile: Dockerfile
    env_file:
      - .db.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - proxy-network

networks:
  proxy-network:
