version: "3.8"

services:
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8004:8000
    env_file:
      - .env
    depends_on:
      - db_postgres
      - db_redis
    networks:
      - proxy-network
  
  web_dev: 
    extends: 
      service: web
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

  web_prod: 
    extends: 
      service: web 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  db_postgres:
    build:
      context: ./db_postgres
      dockerfile: Dockerfile
    volumes:
      - ./db_postgres/data:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - proxy-network

  db_redis:
    build:
      context: ./db_redis
      dockerfile: Dockerfile
    env_file:
      - .env.db
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - proxy-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.db
    ports:
      - "5050:80"
    depends_on:
      - db_postgres
    networks:
      - proxy-network



networks:
  proxy-network:
